#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun  8 00:09:08 2017

@author: pablotempone
"""

import pandas as pd
import matplotlib as mp
import matplotlib.pyplot as plt
import re
import numpy as np
from sklearn import linear_model

lm = linear_model.LinearRegression()

X = train.drop('rating',axis = 1)

reg_lineal = lm.fit(X,train.rating)